In [1]:
import pandas as pd
import matplotlib as plt

In [2]:
arf_df = pd.read_csv("./PRAMS ARF/csv/phase8_arf_2016_2021.csv")
std_u_df = pd.read_csv("./PRAMS ARF/csv/phase8_2016_2021_std_u.csv")
miha_df = pd.read_csv("./PRAMS ARF/csv/phase8_2016_2021_std_drug_miha.csv")
op_df = pd.read_csv("./Opioid Supp/phase8_sup_opioid.csv")
op_blwthr_df = pd.read_csv("./Opioid Supp/phase8_sup_opioid_blwthr.csv")

print(arf_df.shape)
print(std_u_df.shape)
print(miha_df.shape)
print(op_df.shape)
print(op_blwthr_df.shape)

C:\Users\Vince\AppData\Local\Temp\ipykernel_15516\2456092483.py:1: DtypeWarning: Columns (457,460,461,462,463,464) have mixed types. Specify dtype option on import or set low_memory=False.
  arf_df = pd.read_csv("./PRAMS ARF/csv/phase8_arf_2016_2021.csv")

(221381, 484)
(15070, 15)
(123460, 55)
(41166, 86)
(5775, 188)

C:\Users\Vince\AppData\Local\Temp\ipykernel_15516\2456092483.py:4: DtypeWarning: Columns (58) have mixed types. Specify dtype option on import or set low_memory=False.
  op_df = pd.read_csv("./Opioid Supp/phase8_sup_opioid.csv")

In [3]:
def overlap(df, cols, thing):
    for i in range(1, len(cols)-1):
        for j in range(i+1, len(cols)):
            # print(f"{i}: {cols[i]} vs {j}: {cols[j]}")
            print(
                f'{cols[i]} and {cols[j]}: {df[(df[cols[i]] == thing) & (df[cols[j]] == thing)].shape[0]}\n')

In [4]:
arf_df.head()

,ID,STATE,HISPANIC,MODECONT,PARTICIP,MODE_PRT,MM_DOB,B_ORDER,BRSTFED,CIG_1TRI,...,FRACE_MULTO_PU,PAT_RACE_PU,PAT_RACE_VT,VT_NONHISPANIC_WHITE,MAT_AGE_NAPHSIS_VT,FAGECOMB_VT,MAT_AGE_NAPHSIS_AK,FAGECOMB_AK,PAT_RACE_PU_AK,MAT_RACE_PU_AK
0,2016AK327002,AK,1.0,2.0,1.0,2.0,NaN,1.0,2.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,2.0
1,2016AK327006,AK,1.0,2.0,1.0,2.0,NaN,1.0,1.0,7.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,2.0,2.0
2,2016AK327007,AK,1.0,1.0,1.0,1.0,NaN,1.0,1.0,4.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,2.0,2.0
3,2016AK327009,AK,1.0,2.0,1.0,2.0,NaN,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3.0,NaN,1.0,2.0
4,2016AK327010,AK,1.0,2.0,1.0,2.0,NaN,1.0,1.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,5.0,NaN,NaN,3.0

## From phase8_2016_2021_std_u

In [5]:
df1 = pd.merge(arf_df, std_u_df, on="ID", how="inner")

In [6]:
df1.shape

(15070, 498)

In [7]:
df1.columns

Index(['ID', 'STATE', 'HISPANIC', 'MODECONT', 'PARTICIP', 'MODE_PRT', 'MM_DOB',
       'B_ORDER', 'BRSTFED', 'CIG_1TRI',
       ...
       'RXPN_NEWRX_RAW', 'RXPN_OLDRX_RAW', 'RXPN_NORX_RAW', 'PNC_DRGTRT',
       'BBY_DRUG_WD', 'RXPN_NEWRX', 'RXPN_OLDRX', 'RXPN_NORX', 'SMK6HUSBX',
       'SMK6OTHX'],
      dtype='object', length=498)

In [8]:
cols = [
    "ID",
    "RXPN_OLDRX",
    "RXPN_NORX",
    "PNC_DRGTRT"
]

df_std_u = df1[cols].copy().dropna(subset=cols[1:], how='all')

df_std_u

                 ID  RXPN_OLDRX  RXPN_NORX  PNC_DRGTRT
2233   2017KY001005         NaN        NaN         1.0
2234   2017KY001006         NaN        NaN         1.0
2235   2017KY001009         NaN        NaN         1.0
2236   2017KY001012         NaN        NaN         1.0
2237   2017KY001013         NaN        NaN         3.0
...             ...         ...        ...         ...
15065  2021ND059065         NaN        NaN         3.0
15066  2021ND059068         NaN        NaN         1.0
15067  2021ND059071         NaN        NaN         1.0
15068  2021ND059072         NaN        NaN         1.0
15069  2021ND059073         NaN        NaN         3.0

[7280 rows x 4 columns]

In [9]:
df_std_u = df_std_u[df_std_u[cols].eq(2).any(axis=1)]
df_std_u

                 ID  RXPN_OLDRX  RXPN_NORX  PNC_DRGTRT
2244   2017KY001020         1.0        2.0         1.0
2284   2017KY001097         2.0        1.0         1.0
2373   2017KY002043         NaN        NaN         2.0
2409   2017KY003006         NaN        NaN         2.0
2436   2017KY003057         NaN        NaN         2.0
...             ...         ...        ...         ...
14714  2021ND052064         NaN        NaN         2.0
14789  2021ND053091         NaN        NaN         2.0
14832  2021ND054073         NaN        NaN         2.0
14875  2021ND055066         NaN        NaN         2.0
14921  2021ND056049         NaN        NaN         2.0

[174 rows x 4 columns]

In [10]:
overlap(df_std_u, cols, thing=2)

RXPN_OLDRX and RXPN_NORX: 4

RXPN_OLDRX and PNC_DRGTRT: 1

RXPN_NORX and PNC_DRGTRT: 7

## From phase8_2016_2021_std_drug_miha

In [11]:
df2 = pd.merge(arf_df, miha_df, on="ID", how="inner")

In [12]:
df2.shape

(123460, 538)

In [13]:
cols_miha = [
    "ID",
    "DRGB_MDN",
    "DRGB_HRN",
    "NJDR_MDN",
    "NJDR_HRN",
    "DRGP_MDN",
    "DRGP_HRN"
]

df_miha = df2[cols_miha].copy().dropna(subset=cols_miha[1:], how='all')
df_miha

,ID,DRGB_MDN,DRGB_HRN,NJDR_MDN,NJDR_HRN,DRGP_MDN,DRGP_HRN
0,2016AK327002,1.0,1.0,NaN,NaN,1.0,1.0
1,2016AK327006,1.0,1.0,NaN,NaN,1.0,1.0
2,2016AK327007,1.0,1.0,NaN,NaN,1.0,1.0
3,2016AK327009,1.0,1.0,NaN,NaN,1.0,1.0
4,2016AK327010,1.0,1.0,NaN,NaN,1.0,1.0
...,...,...,...,...,...,...,...
123455,2021WY177072,1.0,1.0,NaN,NaN,NaN,1.0
123456,2021WY177074,1.0,1.0,NaN,NaN,NaN,1.0
123457,2021WY177075,1.0,1.0,NaN,NaN,NaN,1.0
123458,2021WY177077,1.0,1.0,NaN,NaN,NaN,1.0
123459,2021WY177078,1.0,1.0,NaN,NaN,NaN,1.0

In [14]:
df_miha = df_miha[df_miha[cols_miha].eq(2).any(axis=1)].drop_duplicates()
df_miha

,ID,DRGB_MDN,DRGB_HRN,NJDR_MDN,NJDR_HRN,DRGP_MDN,DRGP_HRN
31,2016AK327057,2.0,1.0,NaN,NaN,2.0,1.0
39,2016AK327072,1.0,1.0,NaN,NaN,2.0,1.0
74,2016AK327130,1.0,2.0,NaN,NaN,1.0,2.0
89,2016AK327148,2.0,1.0,NaN,NaN,2.0,1.0
200,2016AK330064,2.0,2.0,NaN,NaN,2.0,2.0
...,...,...,...,...,...,...,...
122961,2021WV403005,NaN,NaN,NaN,NaN,2.0,2.0
122966,2021WV403012,NaN,NaN,NaN,NaN,1.0,2.0
122974,2021WV403027,NaN,NaN,NaN,NaN,1.0,2.0
123282,2021WY173032,1.0,2.0,NaN,NaN,NaN,2.0
123390,2021WY176009,2.0,1.0,NaN,NaN,NaN,1.0

In [15]:
for col in (cols_miha[1:]):
    counts = df_miha[col].value_counts()
    non = df_miha[col].isna().sum()

    print(f"{counts}\nBlank\t{non}\n")

DRGB_MDN
2.0    400
1.0    128
Name: count, dtype: int64
Blank	457

DRGB_HRN
1.0    332
2.0    249
Name: count, dtype: int64
Blank	404

NJDR_MDN
2.0    28
1.0     3
Name: count, dtype: int64
Blank	954

NJDR_HRN
1.0    20
2.0    11
Name: count, dtype: int64
Blank	954

DRGP_MDN
2.0    559
1.0    125
Name: count, dtype: int64
Blank	301

DRGP_HRN
1.0    514
2.0    286
Name: count, dtype: int64
Blank	185

In [16]:
overlap(df_miha, cols_miha, thing=2)

DRGB_MDN and DRGB_HRN: 118

DRGB_MDN and NJDR_MDN: 0

DRGB_MDN and NJDR_HRN: 0

DRGB_MDN and DRGP_MDN: 204

DRGB_MDN and DRGP_HRN: 39

DRGB_HRN and NJDR_MDN: 0

DRGB_HRN and NJDR_HRN: 0

DRGB_HRN and DRGP_MDN: 60

DRGB_HRN and DRGP_HRN: 89

NJDR_MDN and NJDR_HRN: 8

NJDR_MDN and DRGP_MDN: 0

NJDR_MDN and DRGP_HRN: 0

NJDR_HRN and DRGP_MDN: 0

NJDR_HRN and DRGP_HRN: 0

DRGP_MDN and DRGP_HRN: 153

## From phase8_sup_opioid

In [17]:
df3 = pd.merge(arf_df, op_df, on="ID", how="inner")
print(df3.shape)

(41166, 569)

In [18]:
cols_op = [
    "ID",
    "DP_PPRLC_RX_RAW",
    "DP_PPRLC_FAM_RAW",
    "DP_PPRLC_NRX_RAW",
    "DP_PPRLC_OTH_RAW",
    "DP_PPRUS_RLX_RAW",
    "DP_PPRUS_EMO_RAW",
    "DP_PPRUS_SLP_RAW",
    "DP_PPRUS_HGH_RAW",
    "DP_PPRUS_HOK_RAW",
    "DP_PPRUS_OTH_RAW",
    "DP_PPRCUT_RAW",
    "DP_PPRCUTTBL_RAW",
    "DP_PPRCUTHLP_RAW",
    "DP_MAT_RAW",
    "DRGP_MTH",
    "DRGP_NAL",
    "DRGP_HRN"
]
len(cols_op)

18

In [19]:
df_op = df3[cols_op].copy().dropna(subset=cols_op[1:], how='all')
df_op

,ID,DP_PPRLC_RX_RAW,DP_PPRLC_FAM_RAW,DP_PPRLC_NRX_RAW,DP_PPRLC_OTH_RAW,DP_PPRUS_RLX_RAW,DP_PPRUS_EMO_RAW,DP_PPRUS_SLP_RAW,DP_PPRUS_HGH_RAW,DP_PPRUS_HOK_RAW,DP_PPRUS_OTH_RAW,DP_PPRCUT_RAW,DP_PPRCUTTBL_RAW,DP_PPRCUTHLP_RAW,DP_MAT_RAW,DRGP_MTH,DRGP_NAL,DRGP_HRN
0,2019AL312001,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0
1,2019AL312005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0
2,2019AL312006,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
3,2019AL312007,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
4,2019AL312008,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41161,2021WY177072,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,NaN,1.0,1.0,1.0
41162,2021WY177074,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
41163,2021WY177075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
41164,2021WY177077,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
41165,2021WY177078,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0

In [20]:
df_op = df_op[df_op[cols_op].eq(2).any(axis=1)].drop_duplicates()
df_op

,ID,DP_PPRLC_RX_RAW,DP_PPRLC_FAM_RAW,DP_PPRLC_NRX_RAW,DP_PPRLC_OTH_RAW,DP_PPRUS_RLX_RAW,DP_PPRUS_EMO_RAW,DP_PPRUS_SLP_RAW,DP_PPRUS_HGH_RAW,DP_PPRUS_HOK_RAW,DP_PPRUS_OTH_RAW,DP_PPRCUT_RAW,DP_PPRCUTTBL_RAW,DP_PPRCUTHLP_RAW,DP_MAT_RAW,DRGP_MTH,DRGP_NAL,DRGP_HRN
5,2019AL312009,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0
6,2019AL312013,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,1.0,1.0,1.0
15,2019AL312042,1.0,1.0,2.0,1.0,1.0,2.0,1.0,2.0,2.0,1.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN
25,2019AL312062,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0,NaN,1.0,1.0,1.0
26,2019AL312065,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,2.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41089,2021WY175065,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,1.0
41095,2021WY176005,NaN,NaN,NaN,NaN,NaN,2.0,2.0,NaN,NaN,NaN,1.0,NaN,1.0,1.0,1.0,1.0,1.0
41096,2021WY176009,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,2.0,1.0,1.0
41129,2021WY176062,NaN,NaN,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0
41161,2021WY177072,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,NaN,1.0,1.0,1.0

In [21]:
for col in (cols_op[1:]):
    counts = df_op[col].value_counts()
    non = df_op[col].isna().sum()

    print(f"{counts}\nBlank\t{non}\n")

DP_PPRLC_RX_RAW
1.0    1312
2.0     165
Name: count, dtype: int64
Blank	1805

DP_PPRLC_FAM_RAW
1.0    1355
2.0     110
Name: count, dtype: int64
Blank	1817

DP_PPRLC_NRX_RAW
1.0    1297
2.0     265
Name: count, dtype: int64
Blank	1720

DP_PPRLC_OTH_RAW
1.0    1194
2.0     551
Name: count, dtype: int64
Blank	1537

DP_PPRUS_RLX_RAW
1.0    1199
2.0     414
Name: count, dtype: int64
Blank	1669

DP_PPRUS_EMO_RAW
1.0    1330
2.0     141
Name: count, dtype: int64
Blank	1811

DP_PPRUS_SLP_RAW
1.0    1232
2.0     338
Name: count, dtype: int64
Blank	1712

DP_PPRUS_HGH_RAW
1.0    1362
2.0      81
Name: count, dtype: int64
Blank	1839

DP_PPRUS_HOK_RAW
1.0    1346
2.0      86
Name: count, dtype: int64
Blank	1850

DP_PPRUS_OTH_RAW
2.0    1179
1.0     874
Name: count, dtype: int64
Blank	1229

DP_PPRCUT_RAW
1.0    1641
2.0    1035
Name: count, dtype: int64
Blank	606

DP_PPRCUTTBL_RAW
1.0    1296
2.0     189
Name: count, dtype: int64
Blank	1797

DP_PPRCUTHLP_RAW
1.0    1345
2.0     348
Name: count, dtype: int64
Blank	1589

DP_MAT_RAW
1.0    762
2.0    207
Name: count, dtype: int64
Blank	2313

DRGP_MTH
1.0    2680
2.0     488
Name: count, dtype: int64
Blank	114

DRGP_NAL
1.0    3030
2.0     119
Name: count, dtype: int64
Blank	133

DRGP_HRN
1.0    2926
2.0     134
Name: count, dtype: int64
Blank	222

In [22]:
overlap(df_op, cols_op, thing=2)

DP_PPRLC_RX_RAW and DP_PPRLC_FAM_RAW: 38

DP_PPRLC_RX_RAW and DP_PPRLC_NRX_RAW: 23

DP_PPRLC_RX_RAW and DP_PPRLC_OTH_RAW: 11

DP_PPRLC_RX_RAW and DP_PPRUS_RLX_RAW: 43

DP_PPRLC_RX_RAW and DP_PPRUS_EMO_RAW: 22

DP_PPRLC_RX_RAW and DP_PPRUS_SLP_RAW: 33

DP_PPRLC_RX_RAW and DP_PPRUS_HGH_RAW: 18

DP_PPRLC_RX_RAW and DP_PPRUS_HOK_RAW: 18

DP_PPRLC_RX_RAW and DP_PPRUS_OTH_RAW: 37

DP_PPRLC_RX_RAW and DP_PPRCUT_RAW: 56

DP_PPRLC_RX_RAW and DP_PPRCUTTBL_RAW: 16

DP_PPRLC_RX_RAW and DP_PPRCUTHLP_RAW: 20

DP_PPRLC_RX_RAW and DP_MAT_RAW: 11

DP_PPRLC_RX_RAW and DRGP_MTH: 11

DP_PPRLC_RX_RAW and DRGP_NAL: 6

DP_PPRLC_RX_RAW and DRGP_HRN: 4

DP_PPRLC_FAM_RAW and DP_PPRLC_NRX_RAW: 30

DP_PPRLC_FAM_RAW and DP_PPRLC_OTH_RAW: 10

DP_PPRLC_FAM_RAW and DP_PPRUS_RLX_RAW: 41

DP_PPRLC_FAM_RAW and DP_PPRUS_EMO_RAW: 27

DP_PPRLC_FAM_RAW and DP_PPRUS_SLP_RAW: 27

DP_PPRLC_FAM_RAW and DP_PPRUS_HGH_RAW: 18

DP_PPRLC_FAM_RAW and DP_PPRUS_HOK_RAW: 22

DP_PPRLC_FAM_RAW and DP_PPRUS_OTH_RAW: 27

DP_PPRLC_FAM_RAW and DP_PPRCUT_RAW: 44

DP_PPRLC_FAM_RAW and DP_PPRCUTTBL_RAW: 14

DP_PPRLC_FAM_RAW and DP_PPRCUTHLP_RAW: 15

DP_PPRLC_FAM_RAW and DP_MAT_RAW: 13

DP_PPRLC_FAM_RAW and DRGP_MTH: 14

DP_PPRLC_FAM_RAW and DRGP_NAL: 3

DP_PPRLC_FAM_RAW and DRGP_HRN: 4

DP_PPRLC_NRX_RAW and DP_PPRLC_OTH_RAW: 35

DP_PPRLC_NRX_RAW and DP_PPRUS_RLX_RAW: 64

DP_PPRLC_NRX_RAW and DP_PPRUS_EMO_RAW: 47

DP_PPRLC_NRX_RAW and DP_PPRUS_SLP_RAW: 45

DP_PPRLC_NRX_RAW and DP_PPRUS_HGH_RAW: 44

DP_PPRLC_NRX_RAW and DP_PPRUS_HOK_RAW: 46

DP_PPRLC_NRX_RAW and DP_PPRUS_OTH_RAW: 72

DP_PPRLC_NRX_RAW and DP_PPRCUT_RAW: 97

DP_PPRLC_NRX_RAW and DP_PPRCUTTBL_RAW: 49

DP_PPRLC_NRX_RAW and DP_PPRCUTHLP_RAW: 35

DP_PPRLC_NRX_RAW and DP_MAT_RAW: 33

DP_PPRLC_NRX_RAW and DRGP_MTH: 41

DP_PPRLC_NRX_RAW and DRGP_NAL: 8

DP_PPRLC_NRX_RAW and DRGP_HRN: 28

DP_PPRLC_OTH_RAW and DP_PPRUS_RLX_RAW: 30

DP_PPRLC_OTH_RAW and DP_PPRUS_EMO_RAW: 15

DP_PPRLC_OTH_RAW and DP_PPRUS_SLP_RAW: 28

DP_PPRLC_OTH_RAW and DP_PPRUS_HGH_RAW: 14

DP_PPRLC_OTH_RAW and DP_PPRUS_HOK_RAW: 16

DP_PPRLC_OTH_RAW and DP_PPRUS_OTH_RAW: 285

DP_PPRLC_OTH_RAW and DP_PPRCUT_RAW: 102

DP_PPRLC_OTH_RAW and DP_PPRCUTTBL_RAW: 16

DP_PPRLC_OTH_RAW and DP_PPRCUTHLP_RAW: 41

DP_PPRLC_OTH_RAW and DP_MAT_RAW: 27

DP_PPRLC_OTH_RAW and DRGP_MTH: 27

DP_PPRLC_OTH_RAW and DRGP_NAL: 5

DP_PPRLC_OTH_RAW and DRGP_HRN: 10

DP_PPRUS_RLX_RAW and DP_PPRUS_EMO_RAW: 86

DP_PPRUS_RLX_RAW and DP_PPRUS_SLP_RAW: 125

DP_PPRUS_RLX_RAW and DP_PPRUS_HGH_RAW: 43

DP_PPRUS_RLX_RAW and DP_PPRUS_HOK_RAW: 40

DP_PPRUS_RLX_RAW and DP_PPRUS_OTH_RAW: 38

DP_PPRUS_RLX_RAW and DP_PPRCUT_RAW: 146

DP_PPRUS_RLX_RAW and DP_PPRCUTTBL_RAW: 42

DP_PPRUS_RLX_RAW and DP_PPRCUTHLP_RAW: 47

DP_PPRUS_RLX_RAW and DP_MAT_RAW: 39

DP_PPRUS_RLX_RAW and DRGP_MTH: 30

DP_PPRUS_RLX_RAW and DRGP_NAL: 8

DP_PPRUS_RLX_RAW and DRGP_HRN: 22

DP_PPRUS_EMO_RAW and DP_PPRUS_SLP_RAW: 67

DP_PPRUS_EMO_RAW and DP_PPRUS_HGH_RAW: 49

DP_PPRUS_EMO_RAW and DP_PPRUS_HOK_RAW: 42

DP_PPRUS_EMO_RAW and DP_PPRUS_OTH_RAW: 16

DP_PPRUS_EMO_RAW and DP_PPRCUT_RAW: 73

DP_PPRUS_EMO_RAW and DP_PPRCUTTBL_RAW: 33

DP_PPRUS_EMO_RAW and DP_PPRCUTHLP_RAW: 29

DP_PPRUS_EMO_RAW and DP_MAT_RAW: 28

DP_PPRUS_EMO_RAW and DRGP_MTH: 24

DP_PPRUS_EMO_RAW and DRGP_NAL: 6

DP_PPRUS_EMO_RAW and DRGP_HRN: 21

DP_PPRUS_SLP_RAW and DP_PPRUS_HGH_RAW: 43

DP_PPRUS_SLP_RAW and DP_PPRUS_HOK_RAW: 34

DP_PPRUS_SLP_RAW and DP_PPRUS_OTH_RAW: 44

DP_PPRUS_SLP_RAW and DP_PPRCUT_RAW: 106

DP_PPRUS_SLP_RAW and DP_PPRCUTTBL_RAW: 35

DP_PPRUS_SLP_RAW and DP_PPRCUTHLP_RAW: 46

DP_PPRUS_SLP_RAW and DP_MAT_RAW: 27

DP_PPRUS_SLP_RAW and DRGP_MTH: 24

DP_PPRUS_SLP_RAW and DRGP_NAL: 7

DP_PPRUS_SLP_RAW and DRGP_HRN: 22

DP_PPRUS_HGH_RAW and DP_PPRUS_HOK_RAW: 39

DP_PPRUS_HGH_RAW and DP_PPRUS_OTH_RAW: 12

DP_PPRUS_HGH_RAW and DP_PPRCUT_RAW: 51

DP_PPRUS_HGH_RAW and DP_PPRCUTTBL_RAW: 29

DP_PPRUS_HGH_RAW and DP_PPRCUTHLP_RAW: 25

DP_PPRUS_HGH_RAW and DP_MAT_RAW: 22

DP_PPRUS_HGH_RAW and DRGP_MTH: 21

DP_PPRUS_HGH_RAW and DRGP_NAL: 4

DP_PPRUS_HGH_RAW and DRGP_HRN: 20

DP_PPRUS_HOK_RAW and DP_PPRUS_OTH_RAW: 21

DP_PPRUS_HOK_RAW and DP_PPRCUT_RAW: 66

DP_PPRUS_HOK_RAW and DP_PPRCUTTBL_RAW: 47

DP_PPRUS_HOK_RAW and DP_PPRCUTHLP_RAW: 41

DP_PPRUS_HOK_RAW and DP_MAT_RAW: 37

DP_PPRUS_HOK_RAW and DRGP_MTH: 42

DP_PPRUS_HOK_RAW and DRGP_NAL: 7

DP_PPRUS_HOK_RAW and DRGP_HRN: 24

DP_PPRUS_OTH_RAW and DP_PPRCUT_RAW: 213

DP_PPRUS_OTH_RAW and DP_PPRCUTTBL_RAW: 44

DP_PPRUS_OTH_RAW and DP_PPRCUTHLP_RAW: 71

DP_PPRUS_OTH_RAW and DP_MAT_RAW: 39

DP_PPRUS_OTH_RAW and DRGP_MTH: 42

DP_PPRUS_OTH_RAW and DRGP_NAL: 11

DP_PPRUS_OTH_RAW and DRGP_HRN: 6

DP_PPRCUT_RAW and DP_PPRCUTTBL_RAW: 165

DP_PPRCUT_RAW and DP_PPRCUTHLP_RAW: 224

DP_PPRCUT_RAW and DP_MAT_RAW: 109

DP_PPRCUT_RAW and DRGP_MTH: 71

DP_PPRCUT_RAW and DRGP_NAL: 13

DP_PPRCUT_RAW and DRGP_HRN: 32

DP_PPRCUTTBL_RAW and DP_PPRCUTHLP_RAW: 99

DP_PPRCUTTBL_RAW and DP_MAT_RAW: 61

DP_PPRCUTTBL_RAW and DRGP_MTH: 49

DP_PPRCUTTBL_RAW and DRGP_NAL: 9

DP_PPRCUTTBL_RAW and DRGP_HRN: 28

DP_PPRCUTHLP_RAW and DP_MAT_RAW: 135

DP_PPRCUTHLP_RAW and DRGP_MTH: 63

DP_PPRCUTHLP_RAW and DRGP_NAL: 11

DP_PPRCUTHLP_RAW and DRGP_HRN: 25

DP_MAT_RAW and DRGP_MTH: 91

DP_MAT_RAW and DRGP_NAL: 13

DP_MAT_RAW and DRGP_HRN: 27

DRGP_MTH and DRGP_NAL: 97

DRGP_MTH and DRGP_HRN: 93

DRGP_NAL and DRGP_HRN: 32

## from phase8_sup_opioid_blwthr

In [23]:
col_blwthr = [
    "ID",
    "DP_MAT",
    "DP_PPRCUT",
    "DP_PPRCUTHLP",
    "DP_PPRCUTTBL",
    "DP_PPRLC_FAM",
    "DP_PPRLC_NRX",
    "DP_PPRLC_OTH",
    "DP_PPRLC_RX",
    "DP_PPRUS_EMO",
    "DP_PPRUS_HGH",
    "DP_PPRUS_HOK",
    "DP_PPRUS_OTH",
    "DP_PPRUS_RLX",
    "DP_PPRUS_SLP",
]

In [24]:
df_blwthr = op_blwthr_df[col_blwthr].copy().dropna(
    subset=col_blwthr[1:], how='all')


df_blwthr

,ID,DP_MAT,DP_PPRCUT,DP_PPRCUTHLP,DP_PPRCUTTBL,DP_PPRLC_FAM,DP_PPRLC_NRX,DP_PPRLC_OTH,DP_PPRLC_RX,DP_PPRUS_EMO,DP_PPRUS_HGH,DP_PPRUS_HOK,DP_PPRUS_OTH,DP_PPRUS_RLX,DP_PPRUS_SLP
6,2021MD270015,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
13,2021MD270043,2.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
22,2021MD270067,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
48,2021MD271067,NaN,1.0,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0
62,2021MD272038,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5622,2020NV038114,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5664,2020NV040079,NaN,1.0,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0
5742,2020NV042080,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5755,2020NV042110,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
5767,2020NV043091,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [25]:
df_blwthr = df_blwthr[df_blwthr[col_blwthr].eq(
    2).any(axis=1)].drop_duplicates()


df_blwthr

,ID,DP_MAT,DP_PPRCUT,DP_PPRCUTHLP,DP_PPRCUTTBL,DP_PPRLC_FAM,DP_PPRLC_NRX,DP_PPRLC_OTH,DP_PPRLC_RX,DP_PPRUS_EMO,DP_PPRUS_HGH,DP_PPRUS_HOK,DP_PPRUS_OTH,DP_PPRUS_RLX,DP_PPRUS_SLP
13,2021MD270043,2.0,NaN,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0
48,2021MD271067,NaN,1.0,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0
174,2021MD275054,1.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0
175,2021MD275055,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
195,2021MD276014,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5598,2020NV037115,1.0,2.0,2.0,2.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,2.0,1.0,1.0
5622,2020NV038114,NaN,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
5664,2020NV040079,NaN,1.0,NaN,NaN,1.0,1.0,2.0,1.0,1.0,1.0,1.0,2.0,1.0,1.0
5755,2020NV042110,NaN,1.0,NaN,NaN,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0
5767,2020NV043091,1.0,2.0,2.0,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0

In [26]:
for col in (col_blwthr[1:]):
    counts = df_blwthr[col].value_counts()
    non = df_blwthr[col].isna().sum()

    print(f"{counts}\nBlank\t{non}\n")

DP_MAT
2.0    15
1.0     8
Name: count, dtype: int64
Blank	128

DP_PPRCUT
2.0    78
1.0    70
Name: count, dtype: int64
Blank	3

DP_PPRCUTHLP
1.0    58
2.0    23
Name: count, dtype: int64
Blank	70

DP_PPRCUTTBL
1.0    55
2.0    23
Name: count, dtype: int64
Blank	73

DP_PPRLC_FAM
1.0    141
2.0     10
Name: count, dtype: int64
Blank	0

DP_PPRLC_NRX
1.0    132
2.0     19
Name: count, dtype: int64
Blank	0

DP_PPRLC_OTH
1.0    126
2.0     25
Name: count, dtype: int64
Blank	0

DP_PPRLC_RX
1.0    133
2.0     18
Name: count, dtype: int64
Blank	0

DP_PPRUS_EMO
1.0    139
2.0     12
Name: count, dtype: int64
Blank	0

DP_PPRUS_HGH
1.0    146
2.0      5
Name: count, dtype: int64
Blank	0

DP_PPRUS_HOK
1.0    143
2.0      8
Name: count, dtype: int64
Blank	0

DP_PPRUS_OTH
1.0    100
2.0     51
Name: count, dtype: int64
Blank	0

DP_PPRUS_RLX
1.0    128
2.0     23
Name: count, dtype: int64
Blank	0

DP_PPRUS_SLP
1.0    128
2.0     23
Name: count, dtype: int64
Blank	0

In [27]:
overlap(df_blwthr, col_blwthr, thing=2)

DP_MAT and DP_PPRCUT: 14

DP_MAT and DP_PPRCUTHLP: 15

DP_MAT and DP_PPRCUTTBL: 11

DP_MAT and DP_PPRLC_FAM: 3

DP_MAT and DP_PPRLC_NRX: 5

DP_MAT and DP_PPRLC_OTH: 4

DP_MAT and DP_PPRLC_RX: 4

DP_MAT and DP_PPRUS_EMO: 7

DP_MAT and DP_PPRUS_HGH: 3

DP_MAT and DP_PPRUS_HOK: 7

DP_MAT and DP_PPRUS_OTH: 2

DP_MAT and DP_PPRUS_RLX: 6

DP_MAT and DP_PPRUS_SLP: 4

DP_PPRCUT and DP_PPRCUTHLP: 22

DP_PPRCUT and DP_PPRCUTTBL: 23

DP_PPRCUT and DP_PPRLC_FAM: 7

DP_PPRCUT and DP_PPRLC_NRX: 12

DP_PPRCUT and DP_PPRLC_OTH: 13

DP_PPRCUT and DP_PPRLC_RX: 9

DP_PPRCUT and DP_PPRUS_EMO: 9

DP_PPRCUT and DP_PPRUS_HGH: 4

DP_PPRCUT and DP_PPRUS_HOK: 8

DP_PPRCUT and DP_PPRUS_OTH: 17

DP_PPRCUT and DP_PPRUS_RLX: 10

DP_PPRCUT and DP_PPRUS_SLP: 12

DP_PPRCUTHLP and DP_PPRCUTTBL: 14

DP_PPRCUTHLP and DP_PPRLC_FAM: 3

DP_PPRCUTHLP and DP_PPRLC_NRX: 7

DP_PPRCUTHLP and DP_PPRLC_OTH: 5

DP_PPRCUTHLP and DP_PPRLC_RX: 4

DP_PPRCUTHLP and DP_PPRUS_EMO: 7

DP_PPRCUTHLP and DP_PPRUS_HGH: 3

DP_PPRCUTHLP and DP_PPRUS_HOK: 8

DP_PPRCUTHLP and DP_PPRUS_OTH: 5

DP_PPRCUTHLP and DP_PPRUS_RLX: 7

DP_PPRCUTHLP and DP_PPRUS_SLP: 5

DP_PPRCUTTBL and DP_PPRLC_FAM: 5

DP_PPRCUTTBL and DP_PPRLC_NRX: 6

DP_PPRCUTTBL and DP_PPRLC_OTH: 7

DP_PPRCUTTBL and DP_PPRLC_RX: 2

DP_PPRCUTTBL and DP_PPRUS_EMO: 6

DP_PPRCUTTBL and DP_PPRUS_HGH: 3

DP_PPRCUTTBL and DP_PPRUS_HOK: 7

DP_PPRCUTTBL and DP_PPRUS_OTH: 3

DP_PPRCUTTBL and DP_PPRUS_RLX: 6

DP_PPRCUTTBL and DP_PPRUS_SLP: 6

DP_PPRLC_FAM and DP_PPRLC_NRX: 5

DP_PPRLC_FAM and DP_PPRLC_OTH: 1

DP_PPRLC_FAM and DP_PPRLC_RX: 3

DP_PPRLC_FAM and DP_PPRUS_EMO: 3

DP_PPRLC_FAM and DP_PPRUS_HGH: 2

DP_PPRLC_FAM and DP_PPRUS_HOK: 2

DP_PPRLC_FAM and DP_PPRUS_OTH: 2

DP_PPRLC_FAM and DP_PPRUS_RLX: 4

DP_PPRLC_FAM and DP_PPRUS_SLP: 5

DP_PPRLC_NRX and DP_PPRLC_OTH: 2

DP_PPRLC_NRX and DP_PPRLC_RX: 1

DP_PPRLC_NRX and DP_PPRUS_EMO: 4

DP_PPRLC_NRX and DP_PPRUS_HGH: 2

DP_PPRLC_NRX and DP_PPRUS_HOK: 5

DP_PPRLC_NRX and DP_PPRUS_OTH: 4

DP_PPRLC_NRX and DP_PPRUS_RLX: 8

DP_PPRLC_NRX and DP_PPRUS_SLP: 7

DP_PPRLC_OTH and DP_PPRLC_RX: 0

DP_PPRLC_OTH and DP_PPRUS_EMO: 3

DP_PPRLC_OTH and DP_PPRUS_HGH: 1

DP_PPRLC_OTH and DP_PPRUS_HOK: 3

DP_PPRLC_OTH and DP_PPRUS_OTH: 11

DP_PPRLC_OTH and DP_PPRUS_RLX: 3

DP_PPRLC_OTH and DP_PPRUS_SLP: 2

DP_PPRLC_RX and DP_PPRUS_EMO: 3

DP_PPRLC_RX and DP_PPRUS_HGH: 2

DP_PPRLC_RX and DP_PPRUS_HOK: 2

DP_PPRLC_RX and DP_PPRUS_OTH: 4

DP_PPRLC_RX and DP_PPRUS_RLX: 4

DP_PPRLC_RX and DP_PPRUS_SLP: 4

DP_PPRUS_EMO and DP_PPRUS_HGH: 3

DP_PPRUS_EMO and DP_PPRUS_HOK: 3

DP_PPRUS_EMO and DP_PPRUS_OTH: 1

DP_PPRUS_EMO and DP_PPRUS_RLX: 7

DP_PPRUS_EMO and DP_PPRUS_SLP: 6

DP_PPRUS_HGH and DP_PPRUS_HOK: 3

DP_PPRUS_HGH and DP_PPRUS_OTH: 0

DP_PPRUS_HGH and DP_PPRUS_RLX: 4

DP_PPRUS_HGH and DP_PPRUS_SLP: 2

DP_PPRUS_HOK and DP_PPRUS_OTH: 1

DP_PPRUS_HOK and DP_PPRUS_RLX: 4

DP_PPRUS_HOK and DP_PPRUS_SLP: 3

DP_PPRUS_OTH and DP_PPRUS_RLX: 1

DP_PPRUS_OTH and DP_PPRUS_SLP: 4

DP_PPRUS_RLX and DP_PPRUS_SLP: 9

## Save isolated IDs

In [29]:
std_ids = df_std_u[["ID"]]
miha_ids = df_miha[["ID"]]
op_ids = df_op[["ID"]]
blw_ids = df_blwthr[["ID"]]

In [43]:
arr = [std_ids,
       miha_ids,
       op_ids,
       blw_ids]

for a in arr:
    print(a.shape)

iso_ids = pd.concat(arr).drop_duplicates(
).sort_values("ID").reset_index(drop=True)
iso_ids

(174, 1)
(985, 1)
(3282, 1)
(151, 1)

                ID
0     2016AK327057
1     2016AK327072
2     2016AK327130
3     2016AK327148
4     2016AK330064
...            ...
4358  2021WY175065
4359  2021WY176005
4360  2021WY176009
4361  2021WY176062
4362  2021WY177072

[4363 rows x 1 columns]

In [45]:
iso_ids.to_csv("isolated_abusers.csv", index=False)